# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "PTG project"
title:              "Perceptually-enabled Task Guidance (PTG)"
description:        "The Perceptually-enabled Task Guidance (PTG)"


# URL
url:                https://vida-nyu.github.io/ptg.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/ptg.github.io"
  # - name:           "about"
  #   href:           "/about"
  - name:           "publications"
    href:           "/ptg.github.io/publication"
  - name:           "people"
    href:           "/ptg.github.io/people"
  # - name:           "blog"
    # href:           "/blog"
#   - name:           "abstracts"
#     href:           "/abstracts"
  # - name:           "lab teachings"
  #   href:           "/presentations"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
